site_name: 'Elastic ML Whitelist Guide'
nav:
  - Home: index.md
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
extra_css:
  - stylesheets/extra.css
plugins:
  - search
markdown_extensions:
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
      linenums: true
      noclasses: true
